//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace MissileWP7.MissileServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MissileServiceReference.IMissileService")]
    public interface IMissileService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMissileService/Left", ReplyAction="http://tempuri.org/IMissileService/LeftResponse")]
        System.IAsyncResult BeginLeft(System.AsyncCallback callback, object asyncState);
        
        void EndLeft(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMissileService/Right", ReplyAction="http://tempuri.org/IMissileService/RightResponse")]
        System.IAsyncResult BeginRight(System.AsyncCallback callback, object asyncState);
        
        void EndRight(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMissileService/Up", ReplyAction="http://tempuri.org/IMissileService/UpResponse")]
        System.IAsyncResult BeginUp(System.AsyncCallback callback, object asyncState);
        
        void EndUp(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMissileService/Down", ReplyAction="http://tempuri.org/IMissileService/DownResponse")]
        System.IAsyncResult BeginDown(System.AsyncCallback callback, object asyncState);
        
        void EndDown(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMissileService/Fire", ReplyAction="http://tempuri.org/IMissileService/FireResponse")]
        System.IAsyncResult BeginFire(System.AsyncCallback callback, object asyncState);
        
        void EndFire(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMissileService/Stop", ReplyAction="http://tempuri.org/IMissileService/StopResponse")]
        System.IAsyncResult BeginStop(System.AsyncCallback callback, object asyncState);
        
        void EndStop(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMissileServiceChannel : MissileWP7.MissileServiceReference.IMissileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MissileServiceClient : System.ServiceModel.ClientBase<MissileWP7.MissileServiceReference.IMissileService>, MissileWP7.MissileServiceReference.IMissileService {
        
        private BeginOperationDelegate onBeginLeftDelegate;
        
        private EndOperationDelegate onEndLeftDelegate;
        
        private System.Threading.SendOrPostCallback onLeftCompletedDelegate;
        
        private BeginOperationDelegate onBeginRightDelegate;
        
        private EndOperationDelegate onEndRightDelegate;
        
        private System.Threading.SendOrPostCallback onRightCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpDelegate;
        
        private EndOperationDelegate onEndUpDelegate;
        
        private System.Threading.SendOrPostCallback onUpCompletedDelegate;
        
        private BeginOperationDelegate onBeginDownDelegate;
        
        private EndOperationDelegate onEndDownDelegate;
        
        private System.Threading.SendOrPostCallback onDownCompletedDelegate;
        
        private BeginOperationDelegate onBeginFireDelegate;
        
        private EndOperationDelegate onEndFireDelegate;
        
        private System.Threading.SendOrPostCallback onFireCompletedDelegate;
        
        private BeginOperationDelegate onBeginStopDelegate;
        
        private EndOperationDelegate onEndStopDelegate;
        
        private System.Threading.SendOrPostCallback onStopCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public MissileServiceClient() {
        }
        
        public MissileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MissileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MissileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MissileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> LeftCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> RightCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> UpCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DownCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> FireCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> StopCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MissileWP7.MissileServiceReference.IMissileService.BeginLeft(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLeft(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void MissileWP7.MissileServiceReference.IMissileService.EndLeft(System.IAsyncResult result) {
            base.Channel.EndLeft(result);
        }
        
        private System.IAsyncResult OnBeginLeft(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((MissileWP7.MissileServiceReference.IMissileService)(this)).BeginLeft(callback, asyncState);
        }
        
        private object[] OnEndLeft(System.IAsyncResult result) {
            ((MissileWP7.MissileServiceReference.IMissileService)(this)).EndLeft(result);
            return null;
        }
        
        private void OnLeftCompleted(object state) {
            if ((this.LeftCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LeftCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LeftAsync() {
            this.LeftAsync(null);
        }
        
        public void LeftAsync(object userState) {
            if ((this.onBeginLeftDelegate == null)) {
                this.onBeginLeftDelegate = new BeginOperationDelegate(this.OnBeginLeft);
            }
            if ((this.onEndLeftDelegate == null)) {
                this.onEndLeftDelegate = new EndOperationDelegate(this.OnEndLeft);
            }
            if ((this.onLeftCompletedDelegate == null)) {
                this.onLeftCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLeftCompleted);
            }
            base.InvokeAsync(this.onBeginLeftDelegate, null, this.onEndLeftDelegate, this.onLeftCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MissileWP7.MissileServiceReference.IMissileService.BeginRight(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRight(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void MissileWP7.MissileServiceReference.IMissileService.EndRight(System.IAsyncResult result) {
            base.Channel.EndRight(result);
        }
        
        private System.IAsyncResult OnBeginRight(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((MissileWP7.MissileServiceReference.IMissileService)(this)).BeginRight(callback, asyncState);
        }
        
        private object[] OnEndRight(System.IAsyncResult result) {
            ((MissileWP7.MissileServiceReference.IMissileService)(this)).EndRight(result);
            return null;
        }
        
        private void OnRightCompleted(object state) {
            if ((this.RightCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RightCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RightAsync() {
            this.RightAsync(null);
        }
        
        public void RightAsync(object userState) {
            if ((this.onBeginRightDelegate == null)) {
                this.onBeginRightDelegate = new BeginOperationDelegate(this.OnBeginRight);
            }
            if ((this.onEndRightDelegate == null)) {
                this.onEndRightDelegate = new EndOperationDelegate(this.OnEndRight);
            }
            if ((this.onRightCompletedDelegate == null)) {
                this.onRightCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRightCompleted);
            }
            base.InvokeAsync(this.onBeginRightDelegate, null, this.onEndRightDelegate, this.onRightCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MissileWP7.MissileServiceReference.IMissileService.BeginUp(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUp(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void MissileWP7.MissileServiceReference.IMissileService.EndUp(System.IAsyncResult result) {
            base.Channel.EndUp(result);
        }
        
        private System.IAsyncResult OnBeginUp(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((MissileWP7.MissileServiceReference.IMissileService)(this)).BeginUp(callback, asyncState);
        }
        
        private object[] OnEndUp(System.IAsyncResult result) {
            ((MissileWP7.MissileServiceReference.IMissileService)(this)).EndUp(result);
            return null;
        }
        
        private void OnUpCompleted(object state) {
            if ((this.UpCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpAsync() {
            this.UpAsync(null);
        }
        
        public void UpAsync(object userState) {
            if ((this.onBeginUpDelegate == null)) {
                this.onBeginUpDelegate = new BeginOperationDelegate(this.OnBeginUp);
            }
            if ((this.onEndUpDelegate == null)) {
                this.onEndUpDelegate = new EndOperationDelegate(this.OnEndUp);
            }
            if ((this.onUpCompletedDelegate == null)) {
                this.onUpCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpCompleted);
            }
            base.InvokeAsync(this.onBeginUpDelegate, null, this.onEndUpDelegate, this.onUpCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MissileWP7.MissileServiceReference.IMissileService.BeginDown(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDown(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void MissileWP7.MissileServiceReference.IMissileService.EndDown(System.IAsyncResult result) {
            base.Channel.EndDown(result);
        }
        
        private System.IAsyncResult OnBeginDown(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((MissileWP7.MissileServiceReference.IMissileService)(this)).BeginDown(callback, asyncState);
        }
        
        private object[] OnEndDown(System.IAsyncResult result) {
            ((MissileWP7.MissileServiceReference.IMissileService)(this)).EndDown(result);
            return null;
        }
        
        private void OnDownCompleted(object state) {
            if ((this.DownCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DownCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DownAsync() {
            this.DownAsync(null);
        }
        
        public void DownAsync(object userState) {
            if ((this.onBeginDownDelegate == null)) {
                this.onBeginDownDelegate = new BeginOperationDelegate(this.OnBeginDown);
            }
            if ((this.onEndDownDelegate == null)) {
                this.onEndDownDelegate = new EndOperationDelegate(this.OnEndDown);
            }
            if ((this.onDownCompletedDelegate == null)) {
                this.onDownCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDownCompleted);
            }
            base.InvokeAsync(this.onBeginDownDelegate, null, this.onEndDownDelegate, this.onDownCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MissileWP7.MissileServiceReference.IMissileService.BeginFire(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginFire(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void MissileWP7.MissileServiceReference.IMissileService.EndFire(System.IAsyncResult result) {
            base.Channel.EndFire(result);
        }
        
        private System.IAsyncResult OnBeginFire(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((MissileWP7.MissileServiceReference.IMissileService)(this)).BeginFire(callback, asyncState);
        }
        
        private object[] OnEndFire(System.IAsyncResult result) {
            ((MissileWP7.MissileServiceReference.IMissileService)(this)).EndFire(result);
            return null;
        }
        
        private void OnFireCompleted(object state) {
            if ((this.FireCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.FireCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void FireAsync() {
            this.FireAsync(null);
        }
        
        public void FireAsync(object userState) {
            if ((this.onBeginFireDelegate == null)) {
                this.onBeginFireDelegate = new BeginOperationDelegate(this.OnBeginFire);
            }
            if ((this.onEndFireDelegate == null)) {
                this.onEndFireDelegate = new EndOperationDelegate(this.OnEndFire);
            }
            if ((this.onFireCompletedDelegate == null)) {
                this.onFireCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnFireCompleted);
            }
            base.InvokeAsync(this.onBeginFireDelegate, null, this.onEndFireDelegate, this.onFireCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MissileWP7.MissileServiceReference.IMissileService.BeginStop(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginStop(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void MissileWP7.MissileServiceReference.IMissileService.EndStop(System.IAsyncResult result) {
            base.Channel.EndStop(result);
        }
        
        private System.IAsyncResult OnBeginStop(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((MissileWP7.MissileServiceReference.IMissileService)(this)).BeginStop(callback, asyncState);
        }
        
        private object[] OnEndStop(System.IAsyncResult result) {
            ((MissileWP7.MissileServiceReference.IMissileService)(this)).EndStop(result);
            return null;
        }
        
        private void OnStopCompleted(object state) {
            if ((this.StopCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.StopCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void StopAsync() {
            this.StopAsync(null);
        }
        
        public void StopAsync(object userState) {
            if ((this.onBeginStopDelegate == null)) {
                this.onBeginStopDelegate = new BeginOperationDelegate(this.OnBeginStop);
            }
            if ((this.onEndStopDelegate == null)) {
                this.onEndStopDelegate = new EndOperationDelegate(this.OnEndStop);
            }
            if ((this.onStopCompletedDelegate == null)) {
                this.onStopCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnStopCompleted);
            }
            base.InvokeAsync(this.onBeginStopDelegate, null, this.onEndStopDelegate, this.onStopCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override MissileWP7.MissileServiceReference.IMissileService CreateChannel() {
            return new MissileServiceClientChannel(this);
        }
        
        private class MissileServiceClientChannel : ChannelBase<MissileWP7.MissileServiceReference.IMissileService>, MissileWP7.MissileServiceReference.IMissileService {
            
            public MissileServiceClientChannel(System.ServiceModel.ClientBase<MissileWP7.MissileServiceReference.IMissileService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginLeft(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("Left", _args, callback, asyncState);
                return _result;
            }
            
            public void EndLeft(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("Left", _args, result);
            }
            
            public System.IAsyncResult BeginRight(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("Right", _args, callback, asyncState);
                return _result;
            }
            
            public void EndRight(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("Right", _args, result);
            }
            
            public System.IAsyncResult BeginUp(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("Up", _args, callback, asyncState);
                return _result;
            }
            
            public void EndUp(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("Up", _args, result);
            }
            
            public System.IAsyncResult BeginDown(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("Down", _args, callback, asyncState);
                return _result;
            }
            
            public void EndDown(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("Down", _args, result);
            }
            
            public System.IAsyncResult BeginFire(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("Fire", _args, callback, asyncState);
                return _result;
            }
            
            public void EndFire(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("Fire", _args, result);
            }
            
            public System.IAsyncResult BeginStop(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("Stop", _args, callback, asyncState);
                return _result;
            }
            
            public void EndStop(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("Stop", _args, result);
            }
        }
    }
}
